# Generated by Django 5.0.1 on 2024-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rth', '0002_alter_mpesapayment_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='product/2024-03-12'),
        ),
    ]
